# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/baddog/Desktop/img_sim_fast/img_sim_fast/img_sim/img_sim/img_sim.srcs/sources_1/ip/delay_1hang/delay_1hang.xci
# IP: The module: 'delay_1hang' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/baddog/Desktop/img_sim_fast/img_sim_fast/img_sim/img_sim/img_sim.srcs/sources_1/ip/delay_1hang/delay_1hang_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delay_1hang'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/baddog/Desktop/img_sim_fast/img_sim_fast/img_sim/img_sim/img_sim.srcs/sources_1/ip/delay_1hang/delay_1hang.xci
# IP: The module: 'delay_1hang' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/baddog/Desktop/img_sim_fast/img_sim_fast/img_sim/img_sim/img_sim.srcs/sources_1/ip/delay_1hang/delay_1hang_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delay_1hang'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
