# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/shift_RAM_3X3_1bit/shift_RAM_3X3_1bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shift_RAM_3X3_1bit || ORIG_REF_NAME==shift_RAM_3X3_1bit} -quiet] -quiet
